### ISSUE TITLE
mouseover and mouseclick doesn't work on text

### ISSUE THREAD

**Issue by gabrielfedel** [scholarslab/nl-widget-Text#3]
Hi,

i updated recently to newest neatlineText version, but the mouseOver e mouseClick on text "links" stopped word. If i change the text-public.js by the old version the things works well.

i don't know if it's the problem is because some modifications on neatline that i made...

**Comment by davidmcclure** [comment]
Hey @gabrielfedel,

Hm, not sure what's up - all the tests are passing, and I just tested the most recent versions manually. What changes did you make to Neatline? If possible, I'd try to avoid making direct changes to the Neatline core - that will make it very difficult to upgrade in the future.

Are you seeing any errors in the Javascript console?

**Comment by gabrielfedel** [comment]
Hi @davidmcclure , i'm trying undo my modifications on Neatline to test, but apparently the problem continues

I'm using Neatline 2.3, could be this?

It's happening this problem on javascript, when a mouseover the links:

TypeError: this.records is undefined text-public.js (linha 1, col 2548)

**Comment by erochest** [comment]
Hi @gabrielfedel ,

I just checked the latest NeatlineText release with Neatline 2.3.0, and it seems to work fine. I also don't see the TypeError that you mention in your post.

**Comment by arojascastro** [comment]
Hello @erochest,
I think I haven encountered the same problem. I intsalled Omeka (v2.3.1.) in my server and after activiting Neatline (v2.4.2.) and Neatline Text (v.1.1.) plugins, I created the slugs for a text in Spanish. The software is uncapable of matching the slugs to the text. I removed the slugs that I created and tried with the sample provided in the documentation just in case: http://www.antoniorojascastro.com/geoepic/neatline/show/soledades  
Any idea about what might be wrong?
Thanks in advance

**Comment by davidmcclure** [comment]
Hey @arojascastro,

Did you enable Neatline Text for the exhibit? Looking at the CSS styles on the spans - I don't think the text plugin is getting loaded for the exhibit.

As for getting the spans to link up with the exhibit - do you have records in the exhibit with slugs that correspond to the text? Eg, is there a record with a slug of "asia"?

**Comment by arojascastro** [comment]
Hi @davidmcclure, 
Thanks a lot. The problem was that I did not select the widget "Text" in the Exhibit Settings. :-/ 

It is all right now! 

Thanks for your help
